apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
  namespace: default
spec:
  entrypoint: myentry
  templates:
    - name: myentry
      steps:
        - - name: step1
            template: hello-windows
        - - name: step2
            template: hello-linux
    - name: hello-windows
      nodeSelector:
        kubernetes.io/os: windows  # step runs on Windows
      container:
        image: mcr.microsoft.com/windows/nanoserver:1809
        command: ["cmd", "/c"]
        args: ["echo", "Hello from Windows Container!"]
    - name: hello-linux
      nodeSelector:
        kubernetes.io/os: linux  # step runs on Linux
      container:
        image: alpine
        command: ["echo"]
        args: ["Hello from Linux Container!"]
